### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by RecursiveG** [NyaaCat/nyaautils#1]
See [here](https://bbs.nyaa.cat/d/510)

- [x] 真正的弹射器
- [x] 物品展示
- [x] 博物馆展示
- [x] [高优先] 怪物击杀判定
- [x] [高优先] 战利品保护
- [ ] 动态生物控制
- [ ] 区块预加载控制
- [x] [高优先] 消耗品附魔书自动化
- [x] [高优先] 光源修复
- [ ] 材料修复
- [ ] 自助前后缀

**Comment by phoenixlzx** [comment]
关于自动化附魔，管理组的一些讨论。

* 高等级附魔书每本的附魔等级未必一样所以务必只检查名称和 lore（之前应该说过了
* 消耗附魔修改为直接消耗附魔源中对应附魔的所有等级，不论玩家命令添加多少等级。例如使用某附魔源给普通钻石剑附魔锋利 5，首先检查该附魔源是否存有足够的锋利等级，有则直接移除附魔源上的锋利附魔并将锋利 5 添加到钻石剑。
* 希望能够加入概率式的附魔结果，即：
  * [概率值 1] 附魔大成功，消耗对应附魔并添加所要求的附魔等级到物品上
  * [概率值 2] 附魔成功，消耗对应附魔并添加所要求的 50% 等级到物品上，小数位舍去
  * [概率值 3] 附魔失败，消耗对应附魔等级但不添加到物品上
  * [概率值 4] 附魔大失败，消耗对应附魔等级并损毁物品
  * 四项概率选项均为整形，例如 `100 100 100 100` 即各情况几率均为 25%。
* 加入 `/nu enchant` 的冷却时间（可以在配置文件中更改，单位是 tick
* 在冷却时间内连续使用 `/nu enchant` 时强制不出现「附魔大成功」

**Comment by phoenixlzx** [comment]
更新一项光源修复。玩家可以使用 `/nu fixlighting [optional N]` 或者 `/nu fl [optional N]` 来修复/强制更新附近 N 半径的 chunk 的光源。N 的可接受最大值可以在配置文件中设置。

另外，高优先的功能完成后 @felixonmars 设置下自动构建，插件会开始进入测试服务器测试。

**Comment by phoenixlzx** [comment]
更新 光源修复内置在 FAWE 里，不需要额外实现了。

**Comment by lilydjwg** [comment]
原来那是服务器的 bug 呀……

**Comment by cyilin** [comment]
高优先级的功能都已经基本完成了
关于博物馆物品展示这部分，只要点击展示框时通过聊天栏输出物品信息就可以吧？

**Comment by RecursiveG** [comment]
@cyilin 博物馆物品展示这部分我来写
另外InfernalMobs的掉落还需要IM插件修改，你去发个ticket吧？

**Comment by phoenixlzx** [comment]
目前测试几个功能似乎都没大问题了。需要修改的几个小地方

* 帮助里出现了不可见字符，考虑使用 soft tab 替代
* 附魔源没有做重复判定，同样的附魔书可以重复添加

**Comment by phoenixlzx** [comment]
另外的一些问题

1. 弹射器无论写多小的角度，基本都是 45 度弹射
2. 弹射动能时间太短，如果可能希望优化
3. 需要提示没有权限的 handler 而不是 `cat.nyaa.utils.CommandReceiver$NoPermissionException`

**Comment by RecursiveG** [comment]
Please open new issues for new bugs/feature requests.
