### ISSUE TITLE
关于修改前/后缀的问题

### ISSUE THREAD

**Issue by benpigchu** [NyaaCat/nyaautils#12]
似乎并不能使用带有空格的前/后缀，内容会从空格处截断……

**Comment by Librazy** [comment]
从 https://github.com/NyaaCat/nyaautils/blob/b174f2d8d6d6b22b82d72d34ba5a2f962d23df33/src/main/java/cat/nyaa/nyaautils/CommandHandler.java#L448 这里看起来是会被发一个警告然后什么也不做的才对（

**Comment by benpigchu** [comment]
【 @Librazy  你是不是少看了一个! 】

**Comment by Librazy** [comment]
如果是有空格，后缀似乎会被解释为两个参数？（

**Comment by benpigchu** [comment]
【 @Librazy 看来是这样的（】

**Comment by Librazy** [comment]
所以说为什么并没有返回呢？

**Comment by benpigchu** [comment]
【 @Librazy  比如说我想要一个前缀 "The boxed" ，命令执行之后我的前缀变成了 "The" （ 】

**Comment by RecursiveG** [comment]
考虑使用反引号包裹带有特殊字符的参数，例如：

      `The boxed`

引号中可以使用转义字符

    \`

或

    \\

[链接](https://github.com/NyaaCat/nyaautils/blob/b174f2d8d6d6b22b82d72d34ba5a2f962d23df33/src/main/java/cat/nyaa/utils/CommandReceiver.java#L276)

**Comment by benpigchu** [comment]
【 @RecursiveG  原来是这样啊，感觉应该写在wiki里呢……】

**Comment by Librazy** [comment]
那么……为什么判断没有起作用呢？
