### ISSUE TITLE
使动力胶囊不依赖RPGItems

### ISSUE THREAD

**Issue by RecursiveG** [NyaaCat/nyaautils#15]
注意处理物品的自动更新

**Comment by Librazy** [comment]
然而我的想法是把动力这一套放到RPGitem里，作为鞘翅的一个power，不知道这样可不可行？（并没有读过代码的脑洞系列

**Comment by RecursiveG** [comment]
well... 这样也是一种解决方案。
然而我不是很想再动RPGItems的代码。。。

**Comment by Librazy** [comment]
我是一直觉得这个功能交给RPGItem做不错。现在这个功能用PowerTick是可以实现的，然后还可以拓展出来，拿PowerClick配合做一个一键加速或者定速/定向之类的东西。不过毕竟我还是没有看过代码。。（

**Comment by phoenixlzx** [comment]
这个本来就是 nu 的东西，强行塞给 rpgitems 不合适吧。

**Comment by phoenixlzx** [comment]
于是已经解决。目前使用 RPGitem 通过 `/nu el givefuel` 命令获取燃料胶囊。
