### ISSUE TITLE
Custom events for prefix/suffix/mailbox transaction

### ISSUE THREAD

**Issue by phoenixlzx** [NyaaCat/nyaautils#18]
HamsterEcoHelper/issues/19

配置文件中新增

```
hook_heh: true
```

则 nu 中的所有交易部分（目前只有 prefix/suffix/mailbox）的每一笔**交易额**将计入 HEH 的 `balance`

**Comment by RecursiveG** [comment]
可以考虑发布自定义事件然后在HEH中监听
而不是暴力hook

**Comment by phoenixlzx** [comment]
可以，之前没想到用事件监听的方式。
