### ISSUE TITLE
InfernalMobs使用了不标准的物品掉落方式

### ISSUE THREAD

**Issue by RecursiveG** [NyaaCat/nyaautils#2]
Bukkit 的 `EntityDeathEvent` 事件带有一个物品掉落列表
战利品保护功能（#1）依赖于这个列表。
但是 InfernalMobs 没有使用这个列表，而是在怪物死亡时直接 `getWorld().dropItemNaturally()`
这样导致插件不能确定掉落物品来自哪个怪物，亦无法确定由哪位玩家击杀。

几个可能的解决方案：
1. 修改 InfernalMobs 使其使用这个掉落列表。
2. 使用反射跟踪调用栈进行判断。
3. 依赖 Minecraft 的单线程特性，记录状态进行判断。
个人倾向 1 号方案。

@phoenixlzx @cyilin

**Comment by phoenixlzx** [comment]
赞成 1 号方案，但是会给开发们带来更多压力。每次 InfernalMobs 更新都需要我们应用补丁自己编译一份。

如果可以的话，尝试先联系开发者，直接从上游替换为原生物品掉落列表的方法？

**Comment by RecursiveG** [comment]
然而并找不到上游开发者的REPO...

**Comment by phoenixlzx** [comment]
直接去留言或者开 ticket?
http://dev.bukkit.org/bukkit-plugins/infernal-mobs/

**Comment by cyilin** [comment]
感觉方案一比较好
刚才去看了最早版本(v1.0)是有使用这个掉落物列表的，后来换成非标准方式估计是有某些原因吧...

**Comment by cyilin** [comment]
Infernal Mobs开发者的回复是在loot中设置自定义命令，由nyaautils来给予战利品，但这个命令只能确定玩家击杀了怪物，无法确定是哪个怪物，也无法获取到最大伤害。

**Comment by RecursiveG** [comment]
大概我们需要自己patch了😐

**Comment by phoenixlzx** [comment]
如果没意见的话我们 fork 过来自己维护吧。

还有难处，就再想其他办法。

**Comment by phoenixlzx** [comment]
唔，不用我们自己维护了。我和作者协调过了，本周搞定（应该

接下来开始构建然后测试已有的功能吧。
