### ISSUE TITLE
nu 原版指令增强功能

### ISSUE THREAD

**Issue by miu-wen** [NyaaCat/NyaaUtils#24]
## 描述

将一些常用指令用nu指令进行封装，然后将指令字符串的某些特定字符（例如一些数值）解析为特定规则并执行，以及将同类型指令根据上述规则重复执行的的一种指令增强功能

命令方式例如这样：``` /nu command loop 0 summon zombie {see.x} {random:[~1,~3],type:int} {random:[1,3],type:int} {Motion:[{ramdom:[0,1],type:float},{motionY:1},{motionZ:0.5}]} link summon husk ~ ~ ~ ```

- random:随机数,加入~符号为当前位置的相对位置随机数；
- type:随机数类型；
- motion[X|Y|Z]:玩家所看的的方向的对应xyz轴的动能基础值倍数
- see[X|Y|Z]:玩家所看的方块xyz坐标值
- loop:这条指令循环次数
- link:链接其他指令

字符串解析规则可以直接把rpgitem那边的类似规则弄到这边过来，这样的话就对指令特殊字符串解析就可以独立出来利用了。。。

## 权限

权限节点规则的话可以用 nu.command.*,*为nu command中支持的原版指令名称。

例如：nu.command.summon、nu.command.setblock、nu.command.entitydata

**Comment by RecursiveG** [comment]
指令的发起者并不一定是玩家，而且很多情况会用 Console 作为 Executor，即使这个指令直观上是由玩家触发的。
