### ISSUE TITLE
新功能：地区提示

### ISSUE THREAD

**Issue by phoenixlzx** [NyaaCat/NyaaUtils#25]
summary: 通过 WE 选择一块立方空间设置为 realm，玩家进入该 realm 时展示名称。

配置文件 `config.yml` 部分内容

```
realm:
  default_name: '§aWilderness'
  notification_type: title #option:  title| actionbar | message
```

所有的 realm 保存于 `realm.yml`

### 命令

* `/nu realm create [type] [name] [player id]` 从 WE 的选区创建一个 realm，`type` 可以是 `public` 或 `private`，`name` 是 realm 的名称。如果 `type` 是 `private`，则 `player id` 是必须项，设置该 realm 的所有者。
* `/nu realm info` 查看自己当前所在位置的信息，包括所在世界、坐标和当前 realm 的名称、范围、类型和属主（如果是 private realm 的话）。默认允许所有玩家使用

玩家进入 realm 时展示的信息除名称外还可以包含类型和属主。

**Comment by Librazy** [comment]
realm description: 当前realm的详细介绍
realm setting: 类似Worldguard的region flag的轻量K-V, 提供查询API
