### ISSUE TITLE
无法追踪药水或是环境造成的伤害

### ISSUE THREAD

**Issue by RecursiveG** [NyaaCat/nyaautils#3]
目前尚不能将玩家施加中毒效果或凋零效果造成的伤害计入玩家伤害统计。
同样的，烧伤也不能计入统计。
commit 120b148966fdea7f43adf2839837d600376a6ae4

**Comment by phoenixlzx** [comment]
环境伤害不需要记录，药水可以记录到玩家直接使用的么？村雨这样的武器药水伤害就不需要记录，也不公平。

**Comment by RecursiveG** [comment]
@phoenixlzx 瞬间伤害是可以记录的。

**Comment by phoenixlzx** [comment]
那么干脆只记录直接攻击伤害好了，因为有些药水性武器伤害无法控制，记录了也不科学。

**Comment by RecursiveG** [comment]
箭的攻击也要记录的吧？
但是药水箭就没法记录了。

**Comment by phoenixlzx** [comment]
药水箭用得并不多.... 吧？总之先记录直接伤害咯。
