### ISSUE TITLE
新功能：SignEdit

### ISSUE THREAD

**Issue by phoenixlzx** [NyaaCat/NyaaUtils#35]
一个基本的编辑牌子功能，用于解决垃圾 mojang 的 CJK 支持问题。

管理员部分：

```
/nu se edit [line] [text]|clear
```

修改准星对着的牌子，权限 `nu.se.admin`

玩家部分

**手里拿着**一个木牌，创建一个新的牌子内容（保存在内存里

```
/nu se new
```

然后编辑

```
/nu se sign [line] [text]
```

支持样式代码和字符数量限制

编辑完更新牌子

```
/nu se update
```

更新手中的牌子物品（并清除内存保存的数据），添加 NBT，贴此牌子时即可自动展示文本。权限组 `nu.se.player` 默认 to all

通过此方式绕过记录特定牌子是谁放的... 等等奇葩的问题。

**Comment by liwanglin12** [comment]
SignEdit 独立插件要退役了（
另外这和记录牌子是谁放的有啥关系，那不是CoreProtect的事么

**Comment by cyilin** [comment]
只增加了/nu se edit和/nu se sign两个命令，每次用sign命令编辑后会直接保存到手中的告示牌，直接使用/nu se sign可以显示出手中告示牌的内容。

**Comment by phoenixlzx** [comment]
GJ.
