### ISSUE TITLE
带有经验修补附魔的物品，某些情况下就不能维修到满耐状态了吗？

### ISSUE THREAD

**Issue by tcdw** [NyaaCat/NyaaUtils#37]
今天晚上，我在喵窝服务器通过小黑塔维修带有经验修补附魔的装备，结果发现了一个奇怪的现象：一些物品在维修到距离满耐所需的耐久度还有 1 的时候，就不再被继续维修了。

我尝试把战利品保护关闭，让掉落物与经验球像原版 Minecraft 一样掉落，那些物品就被修好了。

下面是其中三个再也无法在战利品保护开启时继续通过怪物掉落经验维修的物品：

![屏幕快照 2017-11-29 下午8.19.45.png](https://i.loli.net/2017/11/29/5a1ea5fbe85e4.png)
![屏幕快照 2017-11-29 下午8.19.36.png](https://i.loli.net/2017/11/29/5a1ea5fbf3800.png)
![屏幕快照 2017-11-29 下午8.37.26.png](https://i.loli.net/2017/11/29/5a1eaa1da3943.png)

**Comment by RecursiveG** [comment]
设计如此，NyaaUtils采用的修补算法和原版略有出入。
因为一点经验修复两点耐久，为避免浪费经验，需要有至少两点耐久损耗才会进行修补。

**Comment by Librazy** [comment]
我申请打死设计师

**Comment by tcdw** [comment]
好吧，原来是这样。。
不过也没啥问题，除了强迫症部分会无限度发作（

**Comment by liwanglin12** [comment]
This is feature（
