### ISSUE TITLE
a bug in enchant may cause 100% success enchant @EnchatCommand.java:201

### ISSUE THREAD

**Issue by ReinWD** [NyaaCat/NyaaUtils#39]
this line makes "level" to decrease by half.
That means when you apply level 10 enchantment to an item that has level 5 enchantment, only "success" case will do properly.
Example: 
/nu enchant durability
to an item has durability 5 on it.
after several tries, it will make it to set it to level ten, and other cases, it will report input error.

to fix it, please check int "level" first, then choose the random number.

**Comment by ReinWD** [comment]
this bug is reported by Rem_shoushou, reveiewed by me. It's a true problem.

**Comment by Librazy** [comment]
Now it should always fail. Need some test.
