### ISSUE TITLE
Cannot setting prefix and suffix after using EssentialX

### ISSUE THREAD

**Issue by timeance** [NyaaCat/NyaaUtils#40]
换用EssentialX之后就没办法设置前后缀了，请问要怎么解决？
 
![prefix](https://user-images.githubusercontent.com/30307526/34477682-e285ea5c-efd6-11e7-9da0-d7ccaa09f305.jpg)

**Comment by cyilin** [comment]
NyaaCore版本和NyaaUtils不匹配，需要NyaaCore v4.1.63或之后的版本。
https://github.com/NyaaCat/NyaaCore/releases
