### ISSUE TITLE
您好，在Windows系统生成的zh_CN文件乱码

### ISSUE THREAD

**Issue by NTDLX** [NyaaCat/NyaaUtils#47]
可以通过转化为ANSI格式再转回utf-8的形式修正绝大部分字体，但会丢失一部分Unicode字符，通过baidu&Google查阅了相关资料后仍然没有得到解决方案，请问
1、有没有办法解决这个问题；
2、如果在Linux服务器上开服会不会出现这个问题；
3、能否提供一份可以在Windows上正常显示的汉化文件

非常期待&感谢您的回答！

此致
敬礼

**Comment by NTDLX** [comment]
附件：
（1）：将语言修改为zh_CN后自动生成的文件；
（2）：转码为ANSI后的文件；
（3）：将ANSI转为utf-8后的文件。
[(1)zh_CN.txt](https://github.com/NyaaCat/NyaaUtils/files/2087214/1.zh_CN.txt)
[(2)zh_CN.txt](https://github.com/NyaaCat/NyaaUtils/files/2087215/2.zh_CN.txt)
[(3)zh_CN.txt](https://github.com/NyaaCat/NyaaUtils/files/2087216/3.zh_CN.txt)

**Comment by NTDLX** [comment]
非常期待您的答复！！！

**Comment by cyilin** [comment]
这是个bug。。。需要在NyaaCore那边修一下。
你也可以直接用7-zip打开jar，把zh_CN.yml提取到plugins/NyaaUtils，然后启动服务器。不需要转换编码。
