### ISSUE TITLE
NU又空指针异常了

### ISSUE THREAD

**Issue by Ghost-chu** [NyaaCat/NyaaUtils#53]
[Fri, 13. Jul 2018 13:04:37 CST INFO] [Yum] [Yum 事件监控] 插件 NyaaUtils 处理 InventoryClickEvent 事件时发生异常!
[Fri, 13. Jul 2018 13:04:37 CST INFO] [Yum] 异常名称: java.lang.NullPointerException
[Fri, 13. Jul 2018 13:04:37 CST INFO] [Yum] 异常说明: null
[Fri, 13. Jul 2018 13:04:37 CST INFO] [Yum] 简易错误信息如下:
[Fri, 13. Jul 2018 13:04:37 CST INFO] [Yum]     位于 cat.nyaa.nyaautils.elytra.FuelManager.updateItem(FuelManager.java:79)
[Fri, 13. Jul 2018 13:04:37 CST INFO] [Yum]     位于 cat.nyaa.nyaautils.elytra.ElytraEnhanceListener.onInventoryClickEvent(ElytraEnhanceListener.java:90)
[Fri, 13. Jul 2018 13:04:37 CST INFO] [Yum]     位于 com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor907.execute(未知:-1)
[Fri, 13. Jul 2018 13:04:37 CST INFO] [Yum]     位于 org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70)
[Fri, 13. Jul 2018 13:04:37 CST INFO] [Yum]     位于 co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)

**Comment by cyilin** [comment]
无法测试出这个错误
