### ISSUE TITLE
1.13版本诸多问题

### ISSUE THREAD

**Issue by NyanMeow** [NyaaCat/NyaaUtils#54]
1.sethome home back这些收费不支持使用小数点进行收费
![TIM截图20180816184349.png](https://i.loli.net/2018/08/16/5b7555732b66a.png)
2.sethome home back 收费异常：配置文件（false是后来发现问题暂时关了）：
![TIM截图20180816184454.png](https://i.loli.net/2018/08/16/5b7555afe4b1e.png)
但实际却收出来了：
![TIM截图20180816184527.png](https://i.loli.net/2018/08/16/5b7555d691954.png)
3.不支持用床设置家（上面的截图也能反映出来）
4.（HEH问题吧）收到的钱无法入HEH库：后台无提示，直接用指令/heh balance take 也是如此

**Comment by cyilin** [comment]
第四个，请在heh的配置文件中启用balance。

**Comment by NyanMeow** [comment]
第四个解决了
