### ISSUE TITLE
[建议]添加CMI插件支持

### ISSUE THREAD

**Issue by NyanMeow** [NyaaCat/NyaaUtils#55]
CMI插件相比EssentialsX插件在一些方面比ESSX要好多少，也是支持转移ESSX的数据。他也提供了一部分的API可以调用，希望可以添加对此插件的支持
插件连接https://www.spigotmc.org/resources/cmi-240-commands-insane-kits-portals-essentials-economy-mysql-sqlite-much-more.3742/

**Comment by phoenixlzx** [comment]
看了一眼，基本上是 ESSX+NU 部分功能的集合。NU 没有的功能也可以通过原版命令实现，或者通过简单的编码实现。

过多依赖+可靠性问题+功能重合+不开源
因此目前不打算提供对该插件的支持。
