### ISSUE TITLE
Exhibition 添加图书馆支持

### ISSUE THREAD

**Issue by phoenixlzx** [NyaaCat/NyaaUtils#56]
exhibition 保护的物品如果是成书，则右键时打开书的内容（借阅）而不是展示物品。

**Comment by Librazy** [comment]
看了一下现在没有原生 Bukkit/Spigot API 支持，大概需要用NMS搞

**Comment by phoenixlzx** [comment]
NMS 已经塞到 NC 里了就直接用咯。
