### ISSUE TITLE
单纯的发射指令/nu project

### ISSUE THREAD

**Issue by miu-wen** [NyaaCat/nyaautils#6]
感觉如果先tp人物到相对位置上方一格然后强制进入飞行状态再弹飞会效果更好。。。
并且这样玩家可控方向。。。(也更容易自己作死撞壁
各种人间大炮实现可能。。。

顺便，原来那种先弹再飞的方式可以吧飞行部分去掉，变成各种方向弹射或者平射。。。
这样可以作为各种 ~~相当有意思的~~ 机关使用。。。

**Comment by RecursiveG** [comment]
现在改成了这样

    /nu launch <Yaw> <Pitch> <Speed> <Delay> <LaunchSpeed> [Player]

先将玩家Player向Yaw/Pitch方向以Speed速度移动Delay (ticks)的时间
然后展开玩家的鞘翅，按视线方向以LaunchSpeed速度发射

因为有飞行相关的判断代码，所以如果要做单纯的弹射的话，大概需要一个新命令。

**Comment by phoenixlzx** [comment]
弹射器似乎还没完全修复... 弹射过程中应设置玩家飞行状态为开启。

另外，释放并发射时可以添加（~~魔法~~）粒子特效和声音。
